services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    environment:
      DATABASE_URL: sqlite:///./app.db
    volumes:
      - ./backend:/app
    command: bash entrypoint.sh
    networks:
      - webapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ph-api.rule=Host(`ph.berguecio.cl`) && PathPrefix(`/api`)"
      - "traefik.http.routers.ph-api.entrypoints=websecure"
      - "traefik.http.routers.ph-api.tls=true"
      - "traefik.http.services.ph-api.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.ph-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.ph-api.middlewares=ph-api-stripprefix"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - webapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ph.rule=Host(`ph.berguecio.cl`)"
      - "traefik.http.routers.ph.entrypoints=websecure"
      - "traefik.http.routers.ph.tls=true"
      - "traefik.http.services.ph.loadbalancer.server.port=3000"

networks:
  webapp:
    external: true
